name: Checar a versão do .NET

on:
    workflow_dispatch:

jobs:
    check:
        name: Check .NET Version
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
      
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "8.0.300"
