name: Checar a versão do .NET

jobs:
    name: Check
    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "8.0.300"