name: Pipeline CI/CD
run-name: Pipeline Ci/CD executada por ${{ github.actor }} em ${{ github.run_number}}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Building
        working-directory: ./src
        run: dotnet build Review-Filmes.sln

  testes:
    needs: [build]
    uses: JvictorMarques/desafio-cicd-01/.github/workflows/testes.yml@main

  release:
    name: Criação de Release
    runs-on: ubuntu-latest
    needs: [testes]
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src
          file: src/Review-Filmes.Web/Dockerfile
          tags: |
            jvictorsm/projeto-teste:latest
            jvictorsm/projeto-teste:${{ github.run_number }}