name: Execução de Testes

on:
    workflow_call:
    
jobs:
    unity-test:
        name: Teste de Unidade
        runs-on: ubuntu-latest
        steps:
            - name: Setup .NET
              uses: .github/actions/check_version